name: Validate and Deploy Quarto Documents

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # Job 1: Set up R Environment
  setup-r-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # Add any required packages explicitly here
          packages: |
            tidyverse
            quarto
            tinytex
            broom
            brms
            broom.mixed
            knitr

  # Job 2: Validate and Render Quarto Files
  validate-quarto:
    needs: setup-r-environment  # Ensure this runs after setup-r-environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up TinyTeX (for PDF rendering)
        uses: r-lib/actions/setup-tinytex@v2

      - name: Render Quarto Documents
        run: |
          library(quarto)
          qmd_files <- list.files(pattern = "\\.qmd$", recursive = TRUE)
          lapply(qmd_files, function(file) {
            tryCatch({
              quarto::quarto_render(file)
              cat(sprintf("Successfully rendered %s\n", file))
            }, error = function(e) {
              cat(sprintf("Error rendering %s: %s\n", file, e$message))
              quit(status = 1)
            })
          })
        shell: Rscript {0}
